paths:
    prot_feats: "./datasets/COACH420_filtered.pkl"  # 입력 데이터
    save_path: "./results/CV/"                     # K-fold 결과
    result_path: "./results/prediction.tsv"        # 예측 결과
train:
    epochs: 50
    batch_size: 8
    dropout: 0.1
    weight_decay: 0.01
    
architectures:
    hidden_size: 256
    prots_input_dim: 1280
    num_layer: 3
    hidden_act: gelu
    intermediate_size: 512
    num_attention_heads: 8
    context_type: denseaspp
    fusion_mode: concat_project
    k3_dilations: [1,2,3]
    k5_dilations: [2,4,6]
    denseaspp_use_gap: true
    denseaspp_gap_from: input
    denseaspp_bottleneck_ratio: 0.5
    context_dropout: 0.1
    cross_mode: "none"

eval:
    threshold: 0.6
prots:
    max_lengths: 1500
    max_chains: 13